import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export const COLORS = {
    brand: "#D3423E",
    brandDark: "#bb3330",
    bg: "#f9fafb",
    card: "#ffffff",
    border: "#e5e7eb",
    borderLight: "#f3f4f6",
    text: "#111827",
    textMid: "#6b7280",
    textLight: "#9ca3af",
    success: "#16a34a",
    successBg: "#dcfce7",
    warning: "#d97706",
    warningBg: "#fef3c7",
    info: "#2563eb",
    infoBg: "#eff6ff",
    danger: "#dc2626",
    dangerBg: "#fee2e2",
};

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    deliveryImageWrapper: {
        position: "relative",
        height: 110,
        backgroundColor: COLORS.borderLight,
    },
      cardsContainer: {
    paddingHorizontal: 16,
    gap: 12,
  },
    topSafe: { position: "absolute", top: 0, left: 0, right: 0, zIndex: 10 },
    topHeader: {
        marginHorizontal: 16,
        marginTop: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: "#fff",
        borderRadius: 18,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
    backBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: COLORS.borderLight,
        justifyContent: "center",
        alignItems: "center",
    },
    headerTitle: { fontSize: 16, fontWeight: "800", color: COLORS.text },
    headerSubtitle: { fontSize: 11, color: COLORS.textMid, fontWeight: "500", marginTop: 2 },
    routesBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: COLORS.brand,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
    },
    routesBtnText: { color: "#fff", fontSize: 12, fontWeight: "800" },

    loadingPlanBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: COLORS.brand,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 12,
        shadowColor: COLORS.brand,
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 6,
        elevation: 4,
    },
    loadingPlanIcon: {
        width: 26,
        height: 26,
        borderRadius: 8,
        backgroundColor: "rgba(255,255,255,0.25)",
        justifyContent: "center",
        alignItems: "center",
    },
    loadingPlanBtnText: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "800",
        lineHeight: 14,
    },
    loadingPlanBtnSubtext: {
        color: "rgba(255,255,255,0.85)",
        fontSize: 9,
        fontWeight: "700",
        marginTop: 1,
        textTransform: "uppercase",
        letterSpacing: 0.3,
    },

    etaPanel: {
        marginHorizontal: 16,
        marginTop: 8,
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: "#fff",
        borderRadius: 20,
        shadowColor: "#000",
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 18,
        elevation: 10,
    },
    etaTopRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    etaLabel: {
        fontSize: 10,
        fontWeight: "800",
        color: COLORS.textMid,
        letterSpacing: 0.5,
        textTransform: "uppercase",
        marginBottom: 2,
    },
    etaTimeRow: { flexDirection: "row", alignItems: "baseline", gap: 6 },
    etaTime: {
        fontSize: 26,
        fontWeight: "800",
        color: COLORS.text,
        fontVariant: ["tabular-nums"],
    },
    etaClockText: {
        fontSize: 13,
        fontWeight: "700",
        color: COLORS.textMid,
        fontVariant: ["tabular-nums"],
    },
    timerBadgeLarge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: COLORS.warningBg,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
    },
    timerDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.warning },
    timerTextLarge: {
        fontSize: 14,
        fontWeight: "800",
        color: COLORS.warning,
        fontVariant: ["tabular-nums"],
    },
    etaMetaRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderLight,
    },
    etaMetaItem: { flexDirection: "row", alignItems: "center", gap: 5 },
    etaMetaText: { fontSize: 13, fontWeight: "700", color: COLORS.text },
    trafficPill: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 999,
    },
    trafficDot: { width: 6, height: 6, borderRadius: 3 },
    trafficText: { fontSize: 11, fontWeight: "800", letterSpacing: 0.3 },

    searchWrap: { paddingHorizontal: 16, marginTop: 8 },
    searchBox: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#fff",
        paddingHorizontal: 14,
        height: 46,
        borderRadius: 14,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    searchInput: { flex: 1, fontSize: 14, color: COLORS.text, paddingVertical: 0 },

    zoneChipsWrap: { marginTop: 8 },
    zoneChipsContent: { paddingHorizontal: 16, gap: 6, paddingVertical: 2 },
    zoneChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: "#fff",
        borderRadius: 999,
        borderWidth: 1,
        borderColor: COLORS.border,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 2,
    },
    zoneDot: { width: 8, height: 8, borderRadius: 4 },
    zoneChipText: { fontSize: 12, fontWeight: "700", color: COLORS.text },
    zoneChipBadge: {
        backgroundColor: COLORS.borderLight,
        paddingHorizontal: 6,
        paddingVertical: 1,
        borderRadius: 10,
        minWidth: 22,
        alignItems: "center",
    },
    zoneChipBadgeText: { fontSize: 10, fontWeight: "800", color: COLORS.textMid },
    togglePolyChip: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: COLORS.dangerBg,
        borderWidth: 1,
        borderColor: COLORS.brand,
        justifyContent: "center",
        alignItems: "center",
    },

    markerWrapper: { alignItems: "center" },
    markerCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#fff",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 3,
        elevation: 4,
    },
    markerText: { color: "#fff", fontWeight: "800", fontSize: 13 },
    markerArrow: {
        width: 0,
        height: 0,
        borderLeftWidth: 6,
        borderRightWidth: 6,
        borderTopWidth: 7,
        borderLeftColor: "transparent",
        borderRightColor: "transparent",
        marginTop: -2,
    },
    multiOrderBadge: {
        position: "absolute",
        top: -4,
        right: -8,
        backgroundColor: COLORS.warning,
        minWidth: 16,
        height: 16,
        borderRadius: 8,
        paddingHorizontal: 3,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#fff",
    },
    multiOrderBadgeText: {
        color: "#fff",
        fontSize: 9,
        fontWeight: "900",
    },

  cardsWrapper: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: 20,
    zIndex: 5,
  },    emptyScrollContainer: { flexGrow: 1, justifyContent: "center", paddingHorizontal: 16 },
  deliveryImageWrapper: {
    position: "relative",
    height: 110,
    backgroundColor: COLORS.borderLight,
  },  imageBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  imageBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.success,
  },
  imageBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.success,
  },
    clientCard: {
        width: width * 0.78,
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
    clientAvatar: {
        width: 54,
        height: 54,
        borderRadius: 27,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
    },
    clientAvatarImg: { width: "100%", height: "100%" },
    clientInfo: { flex: 1 },
    clientName: { fontSize: 14, fontWeight: "800", color: COLORS.text, marginBottom: 4 },
    clientChipsRow: { flexDirection: "row", gap: 4, marginBottom: 4, flexWrap: "wrap" },
    miniChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 5,
    },
    miniChipText: { fontSize: 9, fontWeight: "800", letterSpacing: 0.3 },
    zoneDotMini: { width: 5, height: 5, borderRadius: 2.5 },
    clientAddressRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    clientAddress: { flex: 1, fontSize: 11, color: COLORS.textMid, fontWeight: "500" },

    routeCard: {
        width: width * 0.78,
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 14,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
    routeCardTop: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
    routeIconBox: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: COLORS.dangerBg,
        justifyContent: "center",
        alignItems: "center",
    },
    routeCardTitle: { fontSize: 14, fontWeight: "800", color: COLORS.text, marginBottom: 2 },
    routeCardDate: { fontSize: 11, color: COLORS.textMid, fontWeight: "600" },
    progressPill: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
    progressPillText: { fontSize: 11, fontWeight: "800" },
    progressTrack: {
        height: 6,
        backgroundColor: COLORS.borderLight,
        borderRadius: 999,
        overflow: "hidden",
        marginBottom: 10,
    },
    cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
    progressFill: { height: "100%", borderRadius: 999 },
    routeCardFooter: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderLight,
    },
    routeCardFooterText: { fontSize: 11, fontWeight: "700", color: COLORS.brand },

    emptyCard: {
        width: width - 32,
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 24,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    emptyCardTitle: { fontSize: 14, fontWeight: "800", color: COLORS.text, marginTop: 10 },
    emptyCardSubtitle: {
        fontSize: 12,
        color: COLORS.textMid,
        marginTop: 4,
        textAlign: "center",
    },
    emptyHorizontalCard: {
        width: width - 32,
        paddingVertical: 28,
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 18,
    },
    emptyHorizontalText: {
        fontSize: 13,
        fontWeight: "700",
        color: COLORS.textMid,
        marginTop: 8,
    },

    stopCard: {
        width: width * 0.78,
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 14,
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
    stopHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    stopNumberBadge: {
        width: 28,
        height: 28,
        borderRadius: 10,
        backgroundColor: COLORS.brand,
        justifyContent: "center",
        alignItems: "center",
    },
    stopNumberText: { color: "#fff", fontSize: 13, fontWeight: "800" },
    statusPill: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
    },
    statusPillText: { fontSize: 10, fontWeight: "800", letterSpacing: 0.4 },
    stopName: { fontSize: 14, fontWeight: "800", color: COLORS.text, marginBottom: 4 },
    stopAddressRow: { flexDirection: "row", alignItems: "flex-start", gap: 4, marginBottom: 8 },
    stopAddress: {
        flex: 1,
        fontSize: 11,
        color: COLORS.textMid,
        fontWeight: "500",
        lineHeight: 15,
    },
    stopFooter: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: COLORS.borderLight,
    },
    stopMultiBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        backgroundColor: COLORS.warning,
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
    },
    stopMultiBadgeText: {
        color: "#fff",
        fontSize: 9,
        fontWeight: "800",
        letterSpacing: 0.3,
    },
    stopBoxesBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        backgroundColor: COLORS.dangerBg,
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 6,
    },
    stopBoxesBadgeText: {
        color: COLORS.brand,
        fontSize: 10,
        fontWeight: "800",
    },
    stopTotal: {
        marginLeft: "auto",
        fontSize: 12,
        fontWeight: "800",
        color: COLORS.text,
    },

    bottomSheet: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "#fff",
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingHorizontal: 20,
        paddingTop: 10,
        maxHeight: height * 0.88,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: -6 },
        shadowRadius: 16,
        elevation: 12,
    },
    modalHandle: {
        alignSelf: "center",
        width: 40,
        height: 4,
        borderRadius: 2,
        backgroundColor: COLORS.border,
        marginBottom: 16,
    },
    bottomSheetHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        marginBottom: 14,
    },
    bottomSheetAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: COLORS.dangerBg,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
    },
    bottomSheetAvatarImg: { width: "100%", height: "100%" },
    bottomSheetAvatarText: {
        fontSize: 16,
        fontWeight: "800",
        color: COLORS.brand,
        letterSpacing: 0.5,
    },
    bottomSheetName: { fontSize: 16, fontWeight: "800", color: COLORS.text },
    bottomSheetAddressRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        marginTop: 3,
    },
    bottomSheetAddress: { flex: 1, fontSize: 12, color: COLORS.textMid, fontWeight: "500" },
    bottomSheetChipsRow: { flexDirection: "row", gap: 4, marginTop: 4, flexWrap: "wrap" },
    bottomSheetMultiBadge: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: COLORS.dangerBg,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
    },
    bottomSheetMultiText: {
        fontSize: 10,
        fontWeight: "800",
        color: COLORS.brand,
        letterSpacing: 0.3,
    },
    bottomSheetClose: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: COLORS.borderLight,
        justifyContent: "center",
        alignItems: "center",
    },

    clientInfoPanel: {
        backgroundColor: COLORS.bg,
        borderRadius: 14,
        padding: 14,
        marginBottom: 12,
    },
    clientInfoLabel: {
        fontSize: 10,
        fontWeight: "800",
        color: COLORS.textMid,
        textTransform: "uppercase",
        letterSpacing: 0.4,
        marginBottom: 10,
    },
    clientInfoRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingVertical: 6,
    },
    clientInfoText: { fontSize: 12, color: COLORS.text, fontWeight: "600" },
    noOrdersInfo: {
        marginTop: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: COLORS.infoBg,
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 10,
    },
    noOrdersText: {
        flex: 1,
        fontSize: 11,
        color: COLORS.info,
        fontWeight: "600",
    },

    tripInfoRow: { flexDirection: "row", gap: 8, marginBottom: 14 },
    tripInfoCard: {
        flex: 1,
        backgroundColor: COLORS.bg,
        borderRadius: 14,
        padding: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    tripInfoIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    tripInfoLabel: {
        fontSize: 10,
        fontWeight: "700",
        color: COLORS.textMid,
        textTransform: "uppercase",
        letterSpacing: 0.4,
    },
    tripInfoValue: { fontSize: 13, fontWeight: "800", color: COLORS.text, marginTop: 1 },

    registeredBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: COLORS.successBg,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
        marginBottom: 12,
    },
    registeredBannerText: {
        flex: 1,
        fontSize: 12,
        fontWeight: "800",
        color: COLORS.success,
        lineHeight: 16,
    },

    bottomSheetActions: { gap: 8, paddingTop: 8 },
    primaryButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 14,
        borderRadius: 14,
        backgroundColor: COLORS.info,
        shadowColor: COLORS.info,
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    successButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 14,
        borderRadius: 14,
        backgroundColor: COLORS.success,
        shadowColor: COLORS.success,
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    brandButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 14,
        borderRadius: 14,
        backgroundColor: COLORS.brand,
        shadowColor: COLORS.brand,
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 10,
        elevation: 4,
    },
    primaryButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0.3,
    },

    deliveredChip: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: COLORS.successBg,
        paddingVertical: 14,
        borderRadius: 14,
    },
    deliveredChipText: {
        color: COLORS.success,
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0.3,
    },

    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(255,255,255,0.7)",
        justifyContent: "center",
        alignItems: "center",
    },
    loadingCard: {
        backgroundColor: "#fff",
        paddingVertical: 24,
        paddingHorizontal: 30,
        borderRadius: 18,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
    loadingText: {
        marginTop: 12,
        color: COLORS.textMid,
        fontSize: 13,
        fontWeight: "600",
    },
    deliveryImageWrapper: {
        position: "relative",
        height: 110,
        backgroundColor: COLORS.borderLight,
    },
    deliveryImage: { width: "100%", height: "100%" },
    deliveryInfo: { padding: 12 },
    deliveryName: {
        fontSize: 14,
        fontWeight: "800",
        color: COLORS.text,
        marginBottom: 6,
    },
      locationRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  cardDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
    marginVertical: 10,
  },
    metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
    metaChipText: { fontSize: 10, fontWeight: "600", color: COLORS.textMid },

      deliveryAddress: {
    flex: 1,
    fontSize: 11,
    color: COLORS.textMid,
    fontWeight: "500",
  },
    deliveryCard: {
        width: 150,
        backgroundColor: "#fff",
        borderRadius: 18,
        overflow: "hidden",
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 6,
    },
});