import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export const COLORS = {
  brand: "#D3423E",
  brandDark: "#bb3330",
  bg: "#f9fafb",
  card: "#ffffff",
  cardSoft: "#f3f4f6",
  border: "#e5e7eb",
  borderLight: "#f3f4f6",
  text: "#111827",
  textMid: "#6b7280",
  textLight: "#9ca3af",
  success: "#16a34a",
  successBg: "#dcfce7",
  warning: "#d97706",
  warningBg: "#fef3c7",
  info: "#2563eb",
  infoBg: "#eff6ff",
  danger: "#dc2626",
  dangerBg: "#fee2e2",
};
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
filterToggle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  filterToggleActive: { backgroundColor: "#fff" },
  heroWrapper: { position: "relative", paddingBottom: 20 },
  heroBg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.brand,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  heroContent: { paddingHorizontal: 20, paddingTop: 8 },
  heroTop: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
    alignItems: "center",
  },
  heroTitle: { color: "#fff", fontSize: 20, fontWeight: "800" },
  heroSubtitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: "500",
    marginTop: 1,
  },

  kpiRow: { flexDirection: "row", gap: 8 },
  kpiCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 3,
  },
  kpiIcon: {
    width: 28,
    height: 28,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
  },
  kpiLabel: { fontSize: 10, color: COLORS.textMid, fontWeight: "600" },
  kpiValue: { fontSize: 14, color: COLORS.text, fontWeight: "800", marginTop: -1 },

  filterBar: {
    flexDirection: "row",
    paddingHorizontal: 20,
    marginTop: 16,
    gap: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.text,
    paddingVertical: 0,
  },

  filterDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },

  filtersPanel: {
    marginHorizontal: 20,
    marginTop: 10,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textMid,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  confirmedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.success,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    marginTop: 6,
  },

  confirmedBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  dateRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    dateInput: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: COLORS.bg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dateInputText: { fontSize: 12, fontWeight: "700", color: COLORS.text },
  dateArrow: { paddingHorizontal: 2 },

  filterActions: { flexDirection: "row", gap: 8, marginTop: 14 },
  clearBtn: {
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  clearBtnText: { fontSize: 12, fontWeight: "700", color: COLORS.textMid },
  applyBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: COLORS.brand,
    justifyContent: "center",
    alignItems: "center",
  },
  applyBtnText: { color: "#fff", fontSize: 13, fontWeight: "800" },

  paymentCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 1,
  },
  paymentCardActive: {
    backgroundColor: "#fff",
    borderColor: COLORS.brand,
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  paymentTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  paymentDateChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  paymentDateText: { fontSize: 10, color: COLORS.textMid, fontWeight: "600" },
  paymentAmount: { fontSize: 22, fontWeight: "800", color: COLORS.text },

  paymentMiddle: { flexDirection: "row", alignItems: "center", gap: 10 },
  paymentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.dangerBg,
    justifyContent: "center",
    alignItems: "center",
  },
  paymentAvatarText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.brand,
    letterSpacing: 0.5,
  },
  paymentClient: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 1,
  },
  paymentNote: { fontSize: 11, color: COLORS.textMid, fontWeight: "600" },

  paymentDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
    marginVertical: 10,
  },

  paymentBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  paymentStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  receiptImageContainer: {
    marginTop: 6,
  },

  receiptImage: {
    width: "100%",
    height: 220,
    borderRadius: 16,
    backgroundColor: COLORS.borderLight,
  },

  noReceiptBox: {
    paddingVertical: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.bg,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },

  noReceiptText: {
    marginTop: 8,
    fontSize: 12,
    color: COLORS.textMid,
    fontWeight: "600",
  },
  paymentStatusText: { fontSize: 10, fontWeight: "800", letterSpacing: 0.4 },

  expandHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  expandHintText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.brand,
    letterSpacing: 0.3,
  },

  receiptWrap: { marginTop: 12 },
  receiptDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.08)",
    marginBottom: 14,
    borderStyle: "dashed",
  },
  receiptHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  receiptIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.dangerBg,
    justifyContent: "center",
    alignItems: "center",
  },
  receiptTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.text,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  receiptMetaRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  receiptMetaItem: { flex: 1 },
  receiptMetaLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: COLORS.textMid,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  receiptMethodPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  receiptMethodText: {
    fontSize: 11,
    fontWeight: "800",
  },
  receiptDueChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: COLORS.bg,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  receiptDueText: { fontSize: 11, fontWeight: "700", color: COLORS.text },

  productsSection: { marginBottom: 12 },
  productsLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textMid,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.04)",
  },
  productQtyBadge: {
    minWidth: 36,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: COLORS.brand,
    justifyContent: "center",
    alignItems: "center",
  },
  productQtyText: { fontSize: 10, fontWeight: "800", color: "#fff" },
  productName: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.text,
    marginBottom: 1,
  },
  productPrice: {
    fontSize: 10,
    color: COLORS.textMid,
    fontWeight: "600",
  },
  productSubtotal: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.text,
  },
  moreProducts: {
    paddingTop: 8,
    alignItems: "center",
  },
  moreProductsText: {
    fontSize: 11,
    color: COLORS.textMid,
    fontWeight: "700",
  },

  totalsCard: {
    backgroundColor: COLORS.bg,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  totalsLabel: { fontSize: 12, color: COLORS.textMid, fontWeight: "600" },
  totalsValue: { fontSize: 13, fontWeight: "800" },
  totalsGrandLabel: { fontSize: 13, color: COLORS.text, fontWeight: "800" },
  totalsGrandValue: { fontSize: 17, fontWeight: "800", color: COLORS.text },

  receiptFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingTop: 4,
  },
  receiptFooterText: {
    fontSize: 10,
    color: COLORS.textLight,
    fontWeight: "600",
  },

  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.text,
    marginTop: 12,
  },
  emptyDesc: {
    fontSize: 12,
    color: COLORS.textMid,
    marginTop: 4,
    textAlign: "center",
  },

  paginationBar: {
    backgroundColor: "#fff",
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 8,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  paginationInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  pageDotsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  pageNavBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: COLORS.dangerBg,
    justifyContent: "center",
    alignItems: "center",
  },
  pageNavBtnDisabled: {
    backgroundColor: COLORS.borderLight,
    opacity: 0.5,
  },
  pageBtn: {
    minWidth: 38,
    height: 38,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: COLORS.borderLight,
    justifyContent: "center",
    alignItems: "center",
  },
  pageBtnActive: {
    backgroundColor: COLORS.brand,
    shadowColor: COLORS.brand,
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    elevation: 4,
  },
  pageText: { fontSize: 13, fontWeight: "700", color: COLORS.textMid },
  pageTextActive: { fontSize: 13, fontWeight: "800", color: "#fff" },
  pageCounter: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: "600",
    color: COLORS.textMid,
  },
  skeletonCard: {
    backgroundColor: "#f3f4f6",
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.04)",
  },
  skeletonTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  skeletonMiddle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  skeletonDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.06)",
    marginBottom: 14,
  },
});